#!/bin/bash
# init.sh - Development Environment Setup
# Generated by Initializer Agent

set -e  # Exit immediately if a command exits with non-zero status
set -u  # Treat unset variables as an error

echo "=== Development Environment Initialization ==="

# Configuration
PORT=${PORT:-3000}
HOST=${HOST:-localhost}

# Check prerequisites
echo "Checking prerequisites..."

# Example: Check for Node.js
# command -v node >/dev/null 2>&1 || { echo "Error: Node.js is required but not installed."; exit 1; }

# Example: Check for required environment variables
# if [ -z "${DATABASE_URL:-}" ]; then
#     echo "Warning: DATABASE_URL not set, using default"
# fi

# Install dependencies if needed
echo "Checking dependencies..."
# Example for Node.js:
# if [ ! -d "node_modules" ]; then
#     echo "Installing npm dependencies..."
#     npm install
# fi

# Example for Python:
# if [ ! -d ".venv" ]; then
#     echo "Creating virtual environment..."
#     python3 -m venv .venv
# fi
# source .venv/bin/activate
# pip install -r requirements.txt

# Database setup (if applicable)
# echo "Setting up database..."
# npm run db:migrate || true

# Start development server
echo "Starting development server on $HOST:$PORT..."

# Example for Node.js/Next.js:
# npm run dev &
# DEV_PID=$!

# Example for Python/Flask:
# flask run --host=$HOST --port=$PORT &
# DEV_PID=$!

# Wait for server to be ready
echo "Waiting for server to start..."
sleep 3

# Health check
echo "Running health check..."
# Example:
# if curl -s "http://$HOST:$PORT/health" > /dev/null; then
#     echo "✓ Server is running at http://$HOST:$PORT"
# else
#     echo "✗ Server failed health check"
#     # kill $DEV_PID 2>/dev/null || true
#     exit 1
# fi

echo ""
echo "=== Environment Ready ==="
echo "Server: http://$HOST:$PORT"
echo "Press Ctrl+C to stop"
echo ""

# Keep script running (adjust based on your setup)
# wait $DEV_PID

# Or for foreground processes:
# npm run dev
